@startuml auth
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor IndianRed
  BorderColor IndianRed
  FontColor #white
}

actor "Anónimo" as Anonimo

package Usuarios #BUSINESS{
  actor Cliente #APPLICATION
  actor Operador #IMPLEMENTATION

  User <|-- Cliente
  User <|-- Operador
}


package "Autenticación y Autorización" #IMPLEMENTATION {
  usecase "registrarse" as registro
  usecase "iniciar sesión" as login
}

Anonimo -up-> registro
Cliente --> login
Operador --> login

@enduml