@startuml operaciones
left to right direction
skinparam actorStyle awesome

skinparam usecase {
  BackgroundColor SkyBlue
  BorderColor LightSkyBlue
}

package Usuarios #BUSINESS{
  actor Operador #IMPLEMENTATION
  User <|-- Operador
}
package "Gestor de operaciones" #APPLICATION {
  usecase "Consultar pedidos" as consultarPedido
  usecase "Ver detalle de un pedido" as verPedido
  usecase "Editar un pedido" as editarPedido
}

Operador --> consultarPedido
Operador --> verPedido
Operador --> editarPedido

@enduml